### PR TITLE
Create ItemsController, add items to users.

### PR DESCRIPTION
**Pull request by hbalenda**

### CODE REVIEW

**Comment by brittanyjspringer** [comment]
@hcbviolet you got ahead of me. :+1:  Tonight, we're going to discuss testing because this PR will need to be at 80% code coverage before I merge in. 

You will know by installing the simplecov gem (and following the instructions [here](https://github.com/colszowka/simplecov)). Create some tests, run rspec and you will see a score print that will tell you your code coverage. 

Talk more tonight!

**Comment by hbalenda** [comment]
@Brit200313 haha, that makes a lot of sense.  Will start looking that over. Talk later!

**Comment by hbalenda** [comment]
@Brit200313 , I added some tests in, coverage is at 98.61%!

**Comment by brittanyjspringer** [comment]
Excellent! :100:

**Pull request merged**
